using System.ComponentModel;
using System.Text.Json;
using Kioku.Mcp.Server.Domain.Coordination;
using Kioku.Mcp.Server.Services;
using ModelContextProtocol.Server;

namespace Kioku.Mcp.Server.Tools;

/// <summary>
/// Thin MCP adapters for the opt-in durable coordination application boundary.
/// </summary>
[McpServerToolType]
public sealed class CoordinationTools(ICoordinationService coordination)
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
        WriteIndented = true,
    };

    [McpServerTool, Description(
        "Initializes a durable coordination run and work item. Empty IDs are generated by the server; " +
        "the operation is idempotent when the same work_item_id and transition_id are retried.")]
    public Task<string> create_coordination_work_item(
        [Description("Project or workflow name associated with the work item.")] string project,
        [Description("Run identity. Empty generates a UUIDv7 run_id.")] string run_id = "",
        [Description("Work-item identity. Empty generates a UUIDv7 work_item_id.")] string work_item_id = "",
        [Description("Attempt identity. Empty generates a UUIDv7 attempt_id.")] string attempt_id = "",
        [Description("Optional durable work-session identity associated with the item.")] string session_id = "",
        [Description("Untrusted diagnostic agent label.")] string agent = "",
        [Description("Comma-separated note: or logical: resource keys protected by the work item.")] string resource_scope = "",
        [Description("Bounded human-readable checkpoint summary.")] string summary = "",
        [Description("Idempotency key for retrying initialization. Empty derives a stable key from work_item_id.")] string transition_id = "",
        McpServer? server = null,
        CancellationToken cancellationToken = default) =>
        ExecuteAsync(() => coordination.CreateWorkItemAsync(
            new CoordinationCreateWorkItemRequest
            {
                RunId = run_id,
                WorkItemId = work_item_id,
                Project = project,
                AttemptId = attempt_id,
                SessionId = session_id,
                Agent = agent,
                ClientName = server?.ClientInfo?.Name,
                ResourceScope = SplitList(resource_scope),
                Summary = summary,
                TransitionId = transition_id,
            },
            cancellationToken));

    [McpServerTool, Description(
        "Returns the current durable coordination projection, active claims, and unresolved conflicts " +
        "for one work item.")]
    public Task<string> get_coordination_work_item(
        [Description("Run identity.")] string run_id,
        [Description("Work-item identity.")] string work_item_id,
        CancellationToken cancellationToken = default) =>
        ExecuteAsync(() => coordination.GetWorkItemAsync(run_id, work_item_id, cancellationToken));

    [McpServerTool, Description("Lists durable coordination work items with optional run, project, and state filters.")]
    public Task<string> list_coordination_work_items(
        [Description("Optional run identity filter.")] string run_id = "",
        [Description("Optional project filter.")] string project = "",
        [Description("Optional state filter: pending, claimed, running, blocked, partial, failed, stale, completed, or canceled.")] string state = "",
        [Description("Number of matching items to skip.")] int offset = 0,
        [Description("Maximum items to return.")] int limit = 20,
        CancellationToken cancellationToken = default) =>
        ExecuteAsync(() => coordination.ListWorkItemsAsync(
            EmptyToNull(run_id),
            EmptyToNull(project),
            EmptyToNull(state),
            offset,
            limit,
            cancellationToken));

    [McpServerTool, Description("Lists durable coordination runs with state counts and last-update timestamps.")]
    public Task<string> list_coordination_runs(
        [Description("Number of matching runs to skip.")] int offset = 0,
        [Description("Maximum runs to return.")] int limit = 20,
        CancellationToken cancellationToken = default) =>
        ExecuteAsync(() => coordination.ListRunsAsync(offset, limit, cancellationToken));

    [McpServerTool, Description(
        "Transitions a work item through the durable state machine. State-changing work normally " +
        "requires the current claim_id and fence_generation; expected_state_version prevents stale reads.")]
    public Task<string> transition_coordination_work_item(
        [Description("Run identity.")] string run_id,
        [Description("Work-item identity.")] string work_item_id,
        [Description("Target state: pending, claimed, running, blocked, partial, failed, stale, completed, or canceled.")] string next_state,
        [Description("Optional explicit event type; the server derives and validates it when empty.")] string event_type = "",
        [Description("Attempt identity; empty uses the current projection.")] string attempt_id = "",
        [Description("Session identity; empty uses the current projection.")] string session_id = "",
        [Description("Idempotency key for the transition. Empty generates a one-shot key.")] string transition_id = "",
        [Description("Expected current state_version. Negative keeps compatibility mode without a version precondition.")] long expected_state_version = -1,
        [Description("Current claim ID protecting the transition.")] string claim_id = "",
        [Description("Current claim fence generation protecting the transition.")] long fence_generation = 0,
        [Description("Untrusted diagnostic agent label.")] string agent = "",
        [Description("Human-readable transition reason or blocker description.")] string reason = "",
        [Description("Safe outcome summary for partial, failed, completed, or canceled states.")] string outcome = "",
        [Description("Stable safe error code for failed or blocked work.")] string error_code = "",
        [Description("Safe reference to a result or resolution artifact.")] string result_reference = "",
        [Description("Safe reference to progress or an in-flight result.")] string progress_reference = "",
        McpServer? server = null,
        CancellationToken cancellationToken = default) =>
        ExecuteAsync(() => coordination.TransitionAsync(
            new CoordinationTransitionRequest
            {
                RunId = run_id,
                WorkItemId = work_item_id,
                NextState = next_state,
                EventType = EmptyToNull(event_type),
                AttemptId = EmptyToNull(attempt_id),
                SessionId = EmptyToNull(session_id),
                TransitionId = EmptyToNull(transition_id),
                ExpectedStateVersion = expected_state_version >= 0 ? expected_state_version : null,
                ClaimId = EmptyToNull(claim_id),
                FenceGeneration = fence_generation > 0 ? fence_generation : null,
                Agent = EmptyToNull(agent),
                ClientName = server?.ClientInfo?.Name,
                Reason = EmptyToNull(reason),
                Outcome = EmptyToNull(outcome),
                ErrorCode = EmptyToNull(error_code),
                ResultReference = EmptyToNull(result_reference),
                ProgressReference = EmptyToNull(progress_reference),
            },
            cancellationToken));

    [McpServerTool, Description("Acquires or takes over the current durable claim for one canonical resource.")]
    public Task<string> acquire_coordination_claim(
        [Description("Run identity.")] string run_id,
        [Description("Work-item identity.")] string work_item_id,
        [Description("Attempt identity.")] string attempt_id,
        [Description("Durable session identity owning the claim.")] string session_id,
        [Description("Canonical note: or logical: resource key.")] string resource_key,
        [Description("Idempotency key for the claim operation.")] string transition_id,
        [Description("Lease duration in seconds, from 1 through 3600.")] int lease_seconds = 30,
        [Description("Untrusted diagnostic agent label.")] string agent = "",
        McpServer? server = null,
        CancellationToken cancellationToken = default) =>
        ExecuteAsync(() => coordination.AcquireClaimAsync(
            new CoordinationClaimAcquireRequest
            {
                RunId = run_id,
                WorkItemId = work_item_id,
                AttemptId = attempt_id,
                SessionId = session_id,
                ResourceKey = resource_key,
                TransitionId = transition_id,
                LeaseDuration = TimeSpan.FromSeconds(lease_seconds),
                Agent = EmptyToNull(agent),
                ClientName = server?.ClientInfo?.Name,
            },
            cancellationToken));

    [McpServerTool, Description("Renews the current claim lease after validating its owner and fence generation.")]
    public Task<string> renew_coordination_claim(
        [Description("Run identity.")] string run_id,
        [Description("Work-item identity.")] string work_item_id,
        [Description("Attempt identity.")] string attempt_id,
        [Description("Durable session identity owning the claim.")] string session_id,
        [Description("Claim identity.")] string claim_id,
        [Description("Canonical note: or logical: resource key.")] string resource_key,
        [Description("Current monotonic fence generation.")] long fence_generation,
        [Description("Idempotency key for the renewal operation.")] string transition_id,
        [Description("New lease duration in seconds, from 1 through 3600.")] int lease_seconds = 30,
        [Description("Optional reason for the renewal.")] string reason = "",
        [Description("Untrusted diagnostic agent label.")] string agent = "",
        McpServer? server = null,
        CancellationToken cancellationToken = default) =>
        ExecuteAsync(() => coordination.RenewClaimAsync(
            new CoordinationClaimMutationRequest
            {
                RunId = run_id,
                WorkItemId = work_item_id,
                AttemptId = attempt_id,
                SessionId = session_id,
                ClaimId = claim_id,
                ResourceKey = resource_key,
                FenceGeneration = fence_generation,
                TransitionId = transition_id,
                LeaseDuration = TimeSpan.FromSeconds(lease_seconds),
                Reason = EmptyToNull(reason),
                Agent = EmptyToNull(agent),
                ClientName = server?.ClientInfo?.Name,
            },
            cancellationToken));

    [McpServerTool, Description("Releases the current claim and returns the updated claim projection.")]
    public Task<string> release_coordination_claim(
        [Description("Run identity.")] string run_id,
        [Description("Work-item identity.")] string work_item_id,
        [Description("Attempt identity.")] string attempt_id,
        [Description("Durable session identity owning the claim.")] string session_id,
        [Description("Claim identity.")] string claim_id,
        [Description("Canonical note: or logical: resource key.")] string resource_key,
        [Description("Current monotonic fence generation.")] long fence_generation,
        [Description("Idempotency key for the release operation.")] string transition_id,
        [Description("Optional reason for releasing the claim.")] string reason = "",
        [Description("Untrusted diagnostic agent label.")] string agent = "",
        McpServer? server = null,
        CancellationToken cancellationToken = default) =>
        ExecuteAsync(() => coordination.ReleaseClaimAsync(
            new CoordinationClaimMutationRequest
            {
                RunId = run_id,
                WorkItemId = work_item_id,
                AttemptId = attempt_id,
                SessionId = session_id,
                ClaimId = claim_id,
                ResourceKey = resource_key,
                FenceGeneration = fence_generation,
                TransitionId = transition_id,
                Reason = EmptyToNull(reason),
                Agent = EmptyToNull(agent),
                ClientName = server?.ClientInfo?.Name,
            },
            cancellationToken));

    [McpServerTool, Description("Observes and persists an expired claim as stale work using server time.")]
    public Task<string> expire_coordination_claim(
        [Description("Run identity.")] string run_id,
        [Description("Work-item identity.")] string work_item_id,
        [Description("Attempt identity.")] string attempt_id,
        [Description("Claim identity.")] string claim_id,
        [Description("Canonical note: or logical: resource key.")] string resource_key,
        [Description("Current monotonic fence generation.")] long fence_generation,
        [Description("Idempotency key for the expiry observation.")] string transition_id,
        [Description("Optional reason for expiry.")] string reason = "",
        CancellationToken cancellationToken = default) =>
        ExecuteAsync(() => coordination.ExpireClaimAsync(
            new CoordinationClaimExpiryRequest
            {
                RunId = run_id,
                WorkItemId = work_item_id,
                AttemptId = attempt_id,
                ClaimId = claim_id,
                ResourceKey = resource_key,
                FenceGeneration = fence_generation,
                TransitionId = transition_id,
                Reason = EmptyToNull(reason),
            },
            cancellationToken));

    [McpServerTool, Description("Lists durable claims with optional run, work-item, and lifecycle filters.")]
    public Task<string> list_coordination_claims(
        [Description("Optional run identity filter.")] string run_id = "",
        [Description("Optional work-item identity filter.")] string work_item_id = "",
        [Description("Optional status filter: active, released, expired, or fenced.")] string status = "",
        [Description("Number of matching claims to skip.")] int offset = 0,
        [Description("Maximum claims to return.")] int limit = 20,
        CancellationToken cancellationToken = default) =>
        ExecuteAsync(() => coordination.ListClaimsAsync(
            EmptyToNull(run_id),
            EmptyToNull(work_item_id),
            EmptyToNull(status),
            offset,
            limit,
            cancellationToken));

    [McpServerTool, Description("Returns ordered, immutable transition history for one work item.")]
    public Task<string> list_coordination_history(
        [Description("Run identity.")] string run_id,
        [Description("Work-item identity.")] string work_item_id,
        [Description("Number of events to skip.")] int offset = 0,
        [Description("Maximum events to return.")] int limit = 50,
        CancellationToken cancellationToken = default) =>
        ExecuteAsync(() => coordination.ListHistoryAsync(run_id, work_item_id, offset, limit, cancellationToken));

    [McpServerTool, Description("Builds a versioned handoff packet from the durable projection and latest history.")]
    public Task<string> get_coordination_handoff(
        [Description("Run identity.")] string run_id,
        [Description("Work-item identity.")] string work_item_id,
        CancellationToken cancellationToken = default) =>
        ExecuteAsync(() => coordination.GetHandoffPacketAsync(run_id, work_item_id, cancellationToken));

    [McpServerTool, Description("Lists work items currently blocked and their safe blocker details.")]
    public Task<string> list_coordination_blockers(
        [Description("Optional run identity filter.")] string run_id = "",
        [Description("Number of blocked items to skip.")] int offset = 0,
        [Description("Maximum blocked items to return.")] int limit = 20,
        CancellationToken cancellationToken = default) =>
        ExecuteAsync(() => coordination.ListWorkItemsAsync(
            EmptyToNull(run_id),
            state: CoordinationStates.Blocked,
            offset: offset,
            limit: limit,
            cancellationToken: cancellationToken));

    [McpServerTool, Description("Lists stale work items and expired claims that require recovery.")]
    public async Task<string> list_stale_coordination_work(
        [Description("Optional run identity filter.")] string run_id = "",
        [Description("Number of stale items to skip.")] int offset = 0,
        [Description("Maximum stale items to return.")] int limit = 20,
        CancellationToken cancellationToken = default)
    {
        try
        {
            var work = await coordination.ListWorkItemsAsync(
                EmptyToNull(run_id),
                state: CoordinationStates.Stale,
                offset: offset,
                limit: limit,
                cancellationToken: cancellationToken);
            var claims = await coordination.ListClaimsAsync(
                EmptyToNull(run_id),
                status: CoordinationClaimStatuses.Expired,
                offset: 0,
                limit: limit,
                cancellationToken: cancellationToken);
            return Serialize(new { work_items = work, expired_claims = claims });
        }
        catch (CoordinationOperationException exception)
        {
            return exception.ToToolError();
        }
    }

    [McpServerTool, Description("Lists failed coordination work items and their safe failure outcomes.")]
    public Task<string> list_failed_coordination_attempts(
        [Description("Optional run identity filter.")] string run_id = "",
        [Description("Number of failed items to skip.")] int offset = 0,
        [Description("Maximum failed items to return.")] int limit = 20,
        CancellationToken cancellationToken = default) =>
        ExecuteAsync(() => coordination.ListWorkItemsAsync(
            EmptyToNull(run_id),
            state: CoordinationStates.Failed,
            offset: offset,
            limit: limit,
            cancellationToken: cancellationToken));

    [McpServerTool, Description("Lists safe coordination conflicts, defaulting to unresolved conflicts.")]
    public Task<string> list_coordination_conflicts(
        [Description("Optional run identity filter.")] string run_id = "",
        [Description("Optional work-item identity filter.")] string work_item_id = "",
        [Description("Status filter: open, resolved, or ignored. Empty means open.")] string status = "open",
        [Description("Number of conflicts to skip.")] int offset = 0,
        [Description("Maximum conflicts to return.")] int limit = 20,
        CancellationToken cancellationToken = default) =>
        ExecuteAsync(() => coordination.ListConflictsAsync(
            EmptyToNull(run_id),
            EmptyToNull(work_item_id),
            EmptyToNull(status),
            offset,
            limit,
            cancellationToken));

    [McpServerTool, Description("Acknowledges or resolves a coordination conflict without rewriting its original evidence.")]
    public Task<string> resolve_coordination_conflict(
        [Description("Conflict identity.")] string conflict_id,
        [Description("Resolution status: resolved or ignored.")] string status,
        [Description("Bounded resolution or acknowledgement note.")] string resolution,
        [Description("Untrusted diagnostic agent label.")] string agent = "",
        [Description("Optional durable session identity recording the resolution.")] string session_id = "",
        McpServer? server = null,
        CancellationToken cancellationToken = default) =>
        ExecuteAsync(() => coordination.ResolveConflictAsync(
            conflict_id,
            status,
            resolution,
            new CoordinationActor
            {
                Agent = EmptyToNull(agent),
                ClientName = server?.ClientInfo?.Name,
                SessionId = EmptyToNull(session_id),
            },
            cancellationToken));

    private static async Task<string> ExecuteAsync<T>(Func<Task<T>> operation)
    {
        try
        {
            return Serialize(await operation().ConfigureAwait(false));
        }
        catch (CoordinationOperationException exception)
        {
            return exception.ToToolError();
        }
        catch (CoordinationClaimException exception)
        {
            return Error(
                exception.Code.ToUpperInvariant(),
                "The coordination claim operation was rejected.",
                "Read the current claim and work-item projection before retrying.");
        }
        catch (CoordinationStoreException)
        {
            return Error(
                CoordinationOperationErrorCodes.CorruptHistory,
                "The coordination history could not be read safely.",
                "Preserve the coordination files and inspect the history before retrying.");
        }
        catch (CoordinationConflictStoreException)
        {
            return Error(
                CoordinationOperationErrorCodes.CorruptHistory,
                "The durable coordination conflict record could not be read safely.",
                "Preserve the coordination files and inspect the conflict record before retrying.");
        }
    }

    private static string Serialize<T>(T value) => JsonSerializer.Serialize(value, JsonOptions);

    private static string Error(string code, string message, string recovery) =>
        $"[error:{code}] {JsonSerializer.Serialize(new { code, message, recovery_action = recovery })}";

    private static string? EmptyToNull(string? value) =>
        string.IsNullOrWhiteSpace(value) ? null : value.Trim();

    private static IReadOnlyList<string> SplitList(string? value) =>
        string.IsNullOrWhiteSpace(value)
            ? []
            : value.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
}
