using System.Text.Json;

namespace Kioku.Mcp.Server.Domain.Coordination;

/// <summary>
/// Stable protocol errors raised by the coordination application boundary.
/// </summary>
public static class CoordinationOperationErrorCodes
{
    public const string AccessDenied = "ACCESS_DENIED";
    public const string ClaimConflict = "CLAIM_CONFLICT";
    public const string ClaimExpired = "CLAIM_EXPIRED";
    public const string ClaimFenced = "CLAIM_SUPERSEDED";
    public const string ClaimRequired = "CLAIM_REQUIRED";
    public const string Conflict = "CONFLICT";
    public const string ConflictAlreadyResolved = "CONFLICT_ALREADY_RESOLVED";
    public const string ConflictNotFound = "CONFLICT_NOT_FOUND";
    public const string CorruptHistory = "CORRUPT_HISTORY";
    public const string DuplicateTransition = "DUPLICATE_TRANSITION";
    public const string Internal = "INTERNAL";
    public const string InvalidArgument = "INVALID_ARGUMENT";
    public const string InvalidState = "INVALID_TRANSITION";
    public const string NotFound = "NOT_FOUND";
    public const string StateVersionConflict = "STATE_VERSION_CONFLICT";
    public const string StaleProjection = "STALE_PROJECTION";
}

/// <summary>
/// Content-safe error returned by coordination tools and resources.
/// </summary>
public sealed class CoordinationOperationException : InvalidOperationException
{
    public CoordinationOperationException(string code, string message, string recoveryAction)
        : base(message)
    {
        Code = code;
        RecoveryAction = recoveryAction;
    }

    public string Code { get; }

    public string RecoveryAction { get; }

    public string ToToolError() =>
        $"[error:{Code}] {JsonSerializer.Serialize(new { code = Code, message = Message, recovery_action = RecoveryAction })}";
}

/// <summary>
/// Initializes one durable run/work-item pair. Empty identities are generated by the server.
/// </summary>
public sealed class CoordinationCreateWorkItemRequest
{
    public string RunId { get; init; } = string.Empty;

    public string WorkItemId { get; init; } = string.Empty;

    public required string Project { get; init; }

    public string? AttemptId { get; init; }

    public string? SessionId { get; init; }

    public string? ParentSessionId { get; init; }

    public string? Agent { get; init; }

    public string? ClientName { get; init; }

    public IReadOnlyList<string> ResourceScope { get; init; } = [];

    public string Summary { get; init; } = "The work item was initialized.";

    public string? TransitionId { get; init; }
}

/// <summary>
/// Requests one state transition after the current projection has been read.
/// </summary>
public sealed class CoordinationTransitionRequest
{
    public required string RunId { get; init; }

    public required string WorkItemId { get; init; }

    public string? AttemptId { get; init; }

    public string? SessionId { get; init; }

    public required string NextState { get; init; }

    public string? EventType { get; init; }

    public string? TransitionId { get; init; }

    public long? ExpectedStateVersion { get; init; }

    public string? ClaimId { get; init; }

    public long? FenceGeneration { get; init; }

    public string? Agent { get; init; }

    public string? ClientName { get; init; }

    public string? Reason { get; init; }

    public string? Outcome { get; init; }

    public string? ErrorCode { get; init; }

    public string? ResultReference { get; init; }

    public string? ProgressReference { get; init; }
}

/// <summary>
/// A read model combining the durable projection with derived claim and conflict visibility.
/// </summary>
public sealed record CoordinationWorkItemSnapshot(
    WorkItemProjection Projection,
    IReadOnlyList<CoordinationClaim> ActiveClaims,
    IReadOnlyList<CoordinationConflict> Conflicts);

/// <summary>
/// A paged coordination result. The fields are intentionally stable for MCP clients.
/// </summary>
public sealed record CoordinationPage<T>(
    IReadOnlyList<T> Items,
    int Total,
    int Offset,
    int Limit,
    bool HasMore);

/// <summary>
/// Compact run-level aggregation used by list_coordination_runs.
/// </summary>
public sealed record CoordinationRunSummary(
    string RunId,
    int WorkItemCount,
    IReadOnlyDictionary<string, int> States,
    DateTimeOffset UpdatedAt);

/// <summary>
/// Result of a state transition, including the updated read model.
/// </summary>
public sealed record CoordinationTransitionResult(
    string Disposition,
    CoordinationEvent Event,
    CoordinationWorkItemSnapshot WorkItem);
