import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import { statSync } from "node:fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the GitHub repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
    ...builtinModules.map((m) => "node:" + m),
  ],
  platform: "node",
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  minify: prod,
  legalComments: "none",
  pure: prod ? ["console.debug"] : [],
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  await context.dispose();

  const bundleBytes = statSync("main.js").size;
  const bundleBudgetBytes = 512 * 1024;
  console.log(`Production bundle: ${(bundleBytes / 1024).toFixed(1)} KiB / 512 KiB budget`);
  if (bundleBytes > bundleBudgetBytes) {
    throw new Error(`main.js exceeds the 512 KiB bundle budget (${bundleBytes} bytes).`);
  }
} else {
  await context.watch();
}
